load("//first_party/publicity:defs.bzl", "public")

PUBLICITY = public()

# Exported because defs.bzl is part of the public API of the publicity system.
exports_files(
    ["defs.bzl"],
    visibility = PUBLICITY,
)
