load("//first_party/publicity:defs.bzl", "public")

PUBLICITY = public()

# Exported because defs.bzl represents the public API of this package.
exports_files(
    ["defs.bzl"],
    visibility = PUBLICITY,
)
