load("@rules_kotlin//kotlin:jvm.bzl", "kt_jvm_test")

kt_jvm_test(
    name = "InputExtTest",
    srcs = [
        "InputExtTest.kt",
    ],
    deps = [
        "//java/com/jackbradshaw/otter/openxr/model:kt_jvm_proto",
        "//java/com/jackbradshaw/otter/openxr/standard",
        "@com_jackbradshaw_maven//:com_google_truth_truth",
        "@com_jackbradshaw_maven//:junit_junit",
        "@com_jackbradshaw_maven//:org_jetbrains_kotlinx_kotlinx_coroutines_core",
    ],
)

kt_jvm_test(
    name = "OutputExtTest",
    srcs = [
        "OutputExtTest.kt",
    ],
    deps = [
        "//java/com/jackbradshaw/otter/openxr/model:kt_jvm_proto",
        "//java/com/jackbradshaw/otter/openxr/standard",
        "@com_jackbradshaw_maven//:com_google_truth_truth",
        "@com_jackbradshaw_maven//:junit_junit",
        "@com_jackbradshaw_maven//:org_jetbrains_kotlinx_kotlinx_coroutines_core",
    ],
)

kt_jvm_test(
    name = "StandardInputComponentTest",
    srcs = [
        "StandardInputComponentTest.kt",
    ],
    deps = [
        "//java/com/jackbradshaw/otter/openxr/standard",
        "@com_jackbradshaw_maven//:com_google_truth_truth",
        "@com_jackbradshaw_maven//:junit_junit",
        "@com_jackbradshaw_maven//:org_jetbrains_kotlinx_kotlinx_coroutines_core",
    ],
)

kt_jvm_test(
    name = "StandardInputIdentifierTest",
    srcs = [
        "StandardInputIdentifierTest.kt",
    ],
    deps = [
        "//java/com/jackbradshaw/otter/openxr/standard",
        "@com_jackbradshaw_maven//:com_google_truth_truth",
        "@com_jackbradshaw_maven//:junit_junit",
        "@com_jackbradshaw_maven//:org_jetbrains_kotlinx_kotlinx_coroutines_core",
    ],
)

kt_jvm_test(
    name = "StandardInputLocationTest",
    srcs = [
        "StandardInputLocationTest.kt",
    ],
    deps = [
        "//java/com/jackbradshaw/otter/openxr/standard",
        "@com_jackbradshaw_maven//:com_google_truth_truth",
        "@com_jackbradshaw_maven//:junit_junit",
        "@com_jackbradshaw_maven//:org_jetbrains_kotlinx_kotlinx_coroutines_core",
    ],
)

kt_jvm_test(
    name = "StandardInteractionProfileTest",
    srcs = [
        "StandardInteractionProfileTest.kt",
    ],
    deps = [
        "//java/com/jackbradshaw/otter/openxr/standard",
        "@com_jackbradshaw_maven//:com_google_truth_truth",
        "@com_jackbradshaw_maven//:junit_junit",
        "@com_jackbradshaw_maven//:org_jetbrains_kotlinx_kotlinx_coroutines_core",
    ],
)

kt_jvm_test(
    name = "StandardOutputLocationTest",
    srcs = [
        "StandardOutputLocationTest.kt",
    ],
    deps = [
        "//java/com/jackbradshaw/otter/openxr/standard",
        "@com_jackbradshaw_maven//:com_google_truth_truth",
        "@com_jackbradshaw_maven//:junit_junit",
        "@com_jackbradshaw_maven//:org_jetbrains_kotlinx_kotlinx_coroutines_core",
    ],
)

kt_jvm_test(
    name = "StandardUserTest",
    srcs = [
        "StandardUserTest.kt",
    ],
    deps = [
        "//java/com/jackbradshaw/otter/openxr/standard",
        "@com_jackbradshaw_maven//:com_google_truth_truth",
        "@com_jackbradshaw_maven//:junit_junit",
        "@com_jackbradshaw_maven//:org_jetbrains_kotlinx_kotlinx_coroutines_core",
    ],
)
