load("@rules_kotlin//kotlin:jvm.bzl", "kt_jvm_library")

package(default_visibility = ["//visibility:public"])

kt_jvm_library(
    name = "worker",
    srcs = ["Worker.kt"],
    deps = ["//first_party/codestone/lifecycle/work"],
)
