filegroup(
    name = "goldens",
    srcs = [
        "generate_decoration_webp_test___generate_decoration_webp__generated_image_matches_golden.webp",
        "generate_gallery_item_webp_test___generate_gallery_item_webp__generated_image_matches_golden.webp",
        "webp_converter_test___optimize_image__normal_conditions__generates_image_matching_golden.webp",
    ],
    visibility = ["//first_party/site/scripts/tests:__pkg__"],
)
