load("@rules_kotlin//kotlin:jvm.bzl", "kt_jvm_binary")

kt_jvm_binary(
    name = "snapshot",
    srcs = ["Snapshot.kt"],
    main_class = "com.jackbradshaw.releasing.SnapshotKt",
    visibility = ["//visibility:public"],
)
