load(":publicity.bzl", "PUBLICITY")

# Exported because these files are the main API of this package.
exports_files(
    [
        "fetch_external_repo.bzl",
        "install_rules_hugo.bzl",
    ],
    visibility = PUBLICITY,
)
