load(":publicity.bzl", "PUBLICITY")

# Exported for repository setup in MODULE.bazel files.
exports_files(
    [
        "fetch_external_repo.bzl",
        "install_rules_hugo.bzl",
    ],
    visibility = PUBLICITY,
)
