load("@rules_kotlin//kotlin:jvm.bzl", "kt_jvm_library")

kt_jvm_library(
    name = "constants",
    testonly = True,
    srcs = [
        "Constants.kt",
    ],
    visibility = [
        "//java/com/jackbradshaw/otter/demo:__subpackages__",
    ],
)
