load("@io_bazel_rules_kotlin//kotlin:jvm.bzl", "kt_jvm_library", "kt_jvm_test")

kt_jvm_test(
    name = "InputComponentExtTest",
    srcs = [
        "InputComponentExtTest.kt",
    ],
    deps = [
        "//java/io/jackbradshaw/otter/openxr/model:proto_extensions",
        "@maven//:com_google_truth_truth",
        "@maven//:junit_junit",
        "@maven//:org_jetbrains_kotlinx_kotlinx_coroutines_core",
    ],
)

kt_jvm_test(
    name = "InputExtTest",
    srcs = [
        "InputExtTest.kt",
    ],
    deps = [
        "//java/io/jackbradshaw/otter/openxr/model:proto_extensions",
        "@maven//:com_google_truth_truth",
        "@maven//:junit_junit",
        "@maven//:org_jetbrains_kotlinx_kotlinx_coroutines_core",
    ],
)

kt_jvm_test(
    name = "InputIdentifierExtTest",
    srcs = [
        "InputIdentifierExtTest.kt",
    ],
    deps = [
        "//java/io/jackbradshaw/otter/openxr/model:proto_extensions",
        "@maven//:com_google_truth_truth",
        "@maven//:junit_junit",
        "@maven//:org_jetbrains_kotlinx_kotlinx_coroutines_core",
    ],
)

kt_jvm_test(
    name = "InputLocationExtTest",
    srcs = [
        "InputLocationExtTest.kt",
    ],
    deps = [
        "//java/io/jackbradshaw/otter/openxr/model:proto_extensions",
        "@maven//:com_google_truth_truth",
        "@maven//:junit_junit",
        "@maven//:org_jetbrains_kotlinx_kotlinx_coroutines_core",
    ],
)

kt_jvm_test(
    name = "InteractionProfileExtTest",
    srcs = [
        "InteractionProfileExtTest.kt",
    ],
    deps = [
        "//java/io/jackbradshaw/otter/openxr/model:proto_extensions",
        "@maven//:com_google_truth_truth",
        "@maven//:junit_junit",
        "@maven//:org_jetbrains_kotlinx_kotlinx_coroutines_core",
    ],
)

kt_jvm_test(
    name = "OutputExtTest",
    srcs = [
        "OutputExtTest.kt",
    ],
    deps = [
        "//java/io/jackbradshaw/otter/openxr/model:proto_extensions",
        "@maven//:com_google_truth_truth",
        "@maven//:junit_junit",
        "@maven//:org_jetbrains_kotlinx_kotlinx_coroutines_core",
    ],
)

kt_jvm_test(
    name = "OutputLocationExtTest",
    srcs = [
        "OutputLocationExtTest.kt",
    ],
    deps = [
        "//java/io/jackbradshaw/otter/openxr/model:proto_extensions",
        "@maven//:com_google_truth_truth",
        "@maven//:junit_junit",
        "@maven//:org_jetbrains_kotlinx_kotlinx_coroutines_core",
    ],
)

kt_jvm_test(
    name = "UserExtTest",
    srcs = [
        "UserExtTest.kt",
    ],
    deps = [
        "//java/io/jackbradshaw/otter/openxr/model:proto_extensions",
        "@maven//:com_google_truth_truth",
        "@maven//:junit_junit",
        "@maven//:org_jetbrains_kotlinx_kotlinx_coroutines_core",
    ],
)
