load("@rules_kotlin//kotlin:jvm.bzl", "kt_jvm_library")

package(default_visibility = ["//visibility:public"])

kt_jvm_library(
    name = "primitives",
    srcs = ["Worker.kt", "Work.kt"],
    deps = ["@com_jackbradshaw_maven//:org_jetbrains_kotlin_kotlin_reflect"],
)
