load("@io_bazel_rules_kotlin//kotlin:jvm.bzl", "kt_jvm_library", "kt_jvm_test")

kt_jvm_test(
    name = "StandardInputComponentTest",
    srcs = [
        "StandardInputComponentTest.kt",
    ],
    deps = [
        "//java/io/jackbradshaw/omnixr/standard",
        "@maven//:com_google_truth_truth",
        "@maven//:junit_junit",
        "@maven//:org_jetbrains_kotlinx_kotlinx_coroutines_core",
    ],
)

kt_jvm_test(
    name = "StandardInputIdentifierTest",
    srcs = [
        "StandardInputIdentifierTest.kt",
    ],
    deps = [
        "//java/io/jackbradshaw/omnixr/standard",
        "@maven//:com_google_truth_truth",
        "@maven//:junit_junit",
        "@maven//:org_jetbrains_kotlinx_kotlinx_coroutines_core",
    ],
)

kt_jvm_test(
    name = "StandardInputLocationTest",
    srcs = [
        "StandardInputLocationTest.kt",
    ],
    deps = [
        "//java/io/jackbradshaw/omnixr/standard",
        "@maven//:com_google_truth_truth",
        "@maven//:junit_junit",
        "@maven//:org_jetbrains_kotlinx_kotlinx_coroutines_core",
    ],
)

kt_jvm_test(
    name = "StandardInteractionProfileTest",
    srcs = [
        "StandardInteractionProfileTest.kt",
    ],
    deps = [
        "//java/io/jackbradshaw/omnixr/standard",
        "@maven//:com_google_truth_truth",
        "@maven//:junit_junit",
        "@maven//:org_jetbrains_kotlinx_kotlinx_coroutines_core",
    ],
)

kt_jvm_test(
    name = "StandardOutputLocationTest",
    srcs = [
        "StandardOutputLocationTest.kt",
    ],
    deps = [
        "//java/io/jackbradshaw/omnixr/standard",
        "@maven//:com_google_truth_truth",
        "@maven//:junit_junit",
        "@maven//:org_jetbrains_kotlinx_kotlinx_coroutines_core",
    ],
)

kt_jvm_test(
    name = "StandardUserTest",
    srcs = [
        "StandardUserTest.kt",
    ],
    deps = [
        "//java/io/jackbradshaw/omnixr/standard",
        "@maven//:com_google_truth_truth",
        "@maven//:junit_junit",
        "@maven//:org_jetbrains_kotlinx_kotlinx_coroutines_core",
    ],
)
