filegroup(
    name = "first_poem",
    srcs = [
        "first_poem.VERSION",
        "first_poem.md",
    ],
)

filegroup(
    name = "borderline",
    srcs = [
        "borderline.VERSION",
        "borderline.md",
    ],
)

filegroup(
    name = "disapproval",
    srcs = [
        "disapproval.VERSION",
        "disapproval.md",
    ],
)

filegroup(
    name = "escape",
    srcs = [
        "escape.VERSION",
        "escape.md",
    ],
)

filegroup(
    name = "pride",
    srcs = [
        "pride.VERSION",
        "pride.md",
    ],
)

filegroup(
    name = "sports_bar",
    srcs = [
        "sports_bar.VERSION",
        "sports_bar.md",
    ],
)
