load("@io_bazel_rules_kotlin//kotlin:jvm.bzl", "kt_jvm_library")

kt_jvm_library(
    name = "constants",
    testonly = True,
    srcs = [
        "Constants.kt",
    ],
    visibility = [
        "//java/io/jackbradshaw/jockstrap/physicsexperiment:__subpackages__",
        "//javatests:__subpackages__",
    ],
)
