load("@aspect_rules_js//js:defs.bzl", "js_library")

js_library(
    name = "npm_deps_must_resolve",
    srcs = ["dummy.js"],
    deps = [
        "//:node_modules/@eslint/js",
        "//:node_modules/@prettier/plugin-xml",
        "//:node_modules/@types/node",
        "//:node_modules/eslint",
        "//:node_modules/prettier",
        "//:node_modules/prettier-plugin-gherkin",
        "//:node_modules/prettier-plugin-sql",
        "//:node_modules/stylelint",
        "//:node_modules/stylelint-config-standard",
        "//:node_modules/typescript",
        "//:node_modules/typescript-eslint",
    ],
)
