load("@rules_kotlin//kotlin:jvm.bzl", "kt_jvm_library")
load("//first_party/dagger:defs.bzl", "kt_jvm_library_with_dagger")

package(default_visibility = ["//visibility:public"])

kt_jvm_library_with_dagger(
    name = "scope",
    srcs = ["ClosetScope.kt"],
)
