/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class IPLAmbisonicsType {
  public final static IPLAmbisonicsType IPL_AMBISONICSTYPE_N3D = new IPLAmbisonicsType("IPL_AMBISONICSTYPE_N3D");
  public final static IPLAmbisonicsType IPL_AMBISONICSTYPE_SN3D = new IPLAmbisonicsType("IPL_AMBISONICSTYPE_SN3D");
  public final static IPLAmbisonicsType IPL_AMBISONICSTYPE_FUMA = new IPLAmbisonicsType("IPL_AMBISONICSTYPE_FUMA");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static IPLAmbisonicsType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + IPLAmbisonicsType.class + " with value " + swigValue);
  }

  private IPLAmbisonicsType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private IPLAmbisonicsType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private IPLAmbisonicsType(String swigName, IPLAmbisonicsType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static IPLAmbisonicsType[] swigValues = { IPL_AMBISONICSTYPE_N3D, IPL_AMBISONICSTYPE_SN3D, IPL_AMBISONICSTYPE_FUMA };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

