/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class IPLAudioBuffer {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected IPLAudioBuffer(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IPLAudioBuffer obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(IPLAudioBuffer obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libphononJNI.delete_IPLAudioBuffer(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setNumChannels(int value) {
    libphononJNI.IPLAudioBuffer_numChannels_set(swigCPtr, this, value);
  }

  public int getNumChannels() {
    return libphononJNI.IPLAudioBuffer_numChannels_get(swigCPtr, this);
  }

  public void setNumSamples(int value) {
    libphononJNI.IPLAudioBuffer_numSamples_set(swigCPtr, this, value);
  }

  public int getNumSamples() {
    return libphononJNI.IPLAudioBuffer_numSamples_get(swigCPtr, this);
  }

  public void setData(SWIGTYPE_p_p_float value) {
    libphononJNI.IPLAudioBuffer_data_set(swigCPtr, this, SWIGTYPE_p_p_float.getCPtr(value));
  }

  public SWIGTYPE_p_p_float getData() {
    long cPtr = libphononJNI.IPLAudioBuffer_data_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_float(cPtr, false);
  }

  public IPLAudioBuffer() {
    this(libphononJNI.new_IPLAudioBuffer(), true);
  }

}
