/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class IPLAudioEffectState {
  public final static IPLAudioEffectState IPL_AUDIOEFFECTSTATE_TAILREMAINING = new IPLAudioEffectState("IPL_AUDIOEFFECTSTATE_TAILREMAINING");
  public final static IPLAudioEffectState IPL_AUDIOEFFECTSTATE_TAILCOMPLETE = new IPLAudioEffectState("IPL_AUDIOEFFECTSTATE_TAILCOMPLETE");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static IPLAudioEffectState swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + IPLAudioEffectState.class + " with value " + swigValue);
  }

  private IPLAudioEffectState(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private IPLAudioEffectState(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private IPLAudioEffectState(String swigName, IPLAudioEffectState swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static IPLAudioEffectState[] swigValues = { IPL_AUDIOEFFECTSTATE_TAILREMAINING, IPL_AUDIOEFFECTSTATE_TAILCOMPLETE };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

