/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class IPLAudioSettings {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected IPLAudioSettings(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IPLAudioSettings obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(IPLAudioSettings obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libphononJNI.delete_IPLAudioSettings(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setSamplingRate(int value) {
    libphononJNI.IPLAudioSettings_samplingRate_set(swigCPtr, this, value);
  }

  public int getSamplingRate() {
    return libphononJNI.IPLAudioSettings_samplingRate_get(swigCPtr, this);
  }

  public void setFrameSize(int value) {
    libphononJNI.IPLAudioSettings_frameSize_set(swigCPtr, this, value);
  }

  public int getFrameSize() {
    return libphononJNI.IPLAudioSettings_frameSize_get(swigCPtr, this);
  }

  public IPLAudioSettings() {
    this(libphononJNI.new_IPLAudioSettings(), true);
  }

}
