/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class IPLAmbisonicsDecodeEffectParams {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected IPLAmbisonicsDecodeEffectParams(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IPLAmbisonicsDecodeEffectParams obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(IPLAmbisonicsDecodeEffectParams obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libphononJNI.delete_IPLAmbisonicsDecodeEffectParams(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setOrder(int value) {
    libphononJNI.IPLAmbisonicsDecodeEffectParams_order_set(swigCPtr, this, value);
  }

  public int getOrder() {
    return libphononJNI.IPLAmbisonicsDecodeEffectParams_order_get(swigCPtr, this);
  }

  public void setHrtf(SWIGTYPE_p__IPLHRTF_t value) {
    libphononJNI.IPLAmbisonicsDecodeEffectParams_hrtf_set(swigCPtr, this, SWIGTYPE_p__IPLHRTF_t.getCPtr(value));
  }

  public SWIGTYPE_p__IPLHRTF_t getHrtf() {
    long cPtr = libphononJNI.IPLAmbisonicsDecodeEffectParams_hrtf_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p__IPLHRTF_t(cPtr, false);
  }

  public void setOrientation(IPLCoordinateSpace3 value) {
    libphononJNI.IPLAmbisonicsDecodeEffectParams_orientation_set(swigCPtr, this, IPLCoordinateSpace3.getCPtr(value), value);
  }

  public IPLCoordinateSpace3 getOrientation() {
    long cPtr = libphononJNI.IPLAmbisonicsDecodeEffectParams_orientation_get(swigCPtr, this);
    return (cPtr == 0) ? null : new IPLCoordinateSpace3(cPtr, false);
  }

  public void setBinaural(IPLbool value) {
    libphononJNI.IPLAmbisonicsDecodeEffectParams_binaural_set(swigCPtr, this, value.swigValue());
  }

  public IPLbool getBinaural() {
    return IPLbool.swigToEnum(libphononJNI.IPLAmbisonicsDecodeEffectParams_binaural_get(swigCPtr, this));
  }

  public IPLAmbisonicsDecodeEffectParams() {
    this(libphononJNI.new_IPLAmbisonicsDecodeEffectParams(), true);
  }

}
