/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class IPLAmbisonicsRotationEffectParams {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected IPLAmbisonicsRotationEffectParams(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IPLAmbisonicsRotationEffectParams obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(IPLAmbisonicsRotationEffectParams obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libphononJNI.delete_IPLAmbisonicsRotationEffectParams(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setOrientation(IPLCoordinateSpace3 value) {
    libphononJNI.IPLAmbisonicsRotationEffectParams_orientation_set(swigCPtr, this, IPLCoordinateSpace3.getCPtr(value), value);
  }

  public IPLCoordinateSpace3 getOrientation() {
    long cPtr = libphononJNI.IPLAmbisonicsRotationEffectParams_orientation_get(swigCPtr, this);
    return (cPtr == 0) ? null : new IPLCoordinateSpace3(cPtr, false);
  }

  public void setOrder(int value) {
    libphononJNI.IPLAmbisonicsRotationEffectParams_order_set(swigCPtr, this, value);
  }

  public int getOrder() {
    return libphononJNI.IPLAmbisonicsRotationEffectParams_order_get(swigCPtr, this);
  }

  public IPLAmbisonicsRotationEffectParams() {
    this(libphononJNI.new_IPLAmbisonicsRotationEffectParams(), true);
  }

}
