/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class IPLAmbisonicsRotationEffectSettings {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected IPLAmbisonicsRotationEffectSettings(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IPLAmbisonicsRotationEffectSettings obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(IPLAmbisonicsRotationEffectSettings obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libphononJNI.delete_IPLAmbisonicsRotationEffectSettings(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setMaxOrder(int value) {
    libphononJNI.IPLAmbisonicsRotationEffectSettings_maxOrder_set(swigCPtr, this, value);
  }

  public int getMaxOrder() {
    return libphononJNI.IPLAmbisonicsRotationEffectSettings_maxOrder_get(swigCPtr, this);
  }

  public IPLAmbisonicsRotationEffectSettings() {
    this(libphononJNI.new_IPLAmbisonicsRotationEffectSettings(), true);
  }

}
