/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class IPLBakedDataVariation {
  public final static IPLBakedDataVariation IPL_BAKEDDATAVARIATION_REVERB = new IPLBakedDataVariation("IPL_BAKEDDATAVARIATION_REVERB");
  public final static IPLBakedDataVariation IPL_BAKEDDATAVARIATION_STATICSOURCE = new IPLBakedDataVariation("IPL_BAKEDDATAVARIATION_STATICSOURCE");
  public final static IPLBakedDataVariation IPL_BAKEDDATAVARIATION_STATICLISTENER = new IPLBakedDataVariation("IPL_BAKEDDATAVARIATION_STATICLISTENER");
  public final static IPLBakedDataVariation IPL_BAKEDDATAVARIATION_DYNAMIC = new IPLBakedDataVariation("IPL_BAKEDDATAVARIATION_DYNAMIC");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static IPLBakedDataVariation swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + IPLBakedDataVariation.class + " with value " + swigValue);
  }

  private IPLBakedDataVariation(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private IPLBakedDataVariation(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private IPLBakedDataVariation(String swigName, IPLBakedDataVariation swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static IPLBakedDataVariation[] swigValues = { IPL_BAKEDDATAVARIATION_REVERB, IPL_BAKEDDATAVARIATION_STATICSOURCE, IPL_BAKEDDATAVARIATION_STATICLISTENER, IPL_BAKEDDATAVARIATION_DYNAMIC };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

