/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class IPLBinauralEffectSettings {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected IPLBinauralEffectSettings(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IPLBinauralEffectSettings obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(IPLBinauralEffectSettings obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libphononJNI.delete_IPLBinauralEffectSettings(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setHrtf(SWIGTYPE_p__IPLHRTF_t value) {
    libphononJNI.IPLBinauralEffectSettings_hrtf_set(swigCPtr, this, SWIGTYPE_p__IPLHRTF_t.getCPtr(value));
  }

  public SWIGTYPE_p__IPLHRTF_t getHrtf() {
    long cPtr = libphononJNI.IPLBinauralEffectSettings_hrtf_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p__IPLHRTF_t(cPtr, false);
  }

  public IPLBinauralEffectSettings() {
    this(libphononJNI.new_IPLBinauralEffectSettings(), true);
  }

}
