/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class IPLBox {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected IPLBox(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IPLBox obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(IPLBox obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libphononJNI.delete_IPLBox(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setMinCoordinates(IPLVector3 value) {
    libphononJNI.IPLBox_minCoordinates_set(swigCPtr, this, IPLVector3.getCPtr(value), value);
  }

  public IPLVector3 getMinCoordinates() {
    long cPtr = libphononJNI.IPLBox_minCoordinates_get(swigCPtr, this);
    return (cPtr == 0) ? null : new IPLVector3(cPtr, false);
  }

  public void setMaxCoordinates(IPLVector3 value) {
    libphononJNI.IPLBox_maxCoordinates_set(swigCPtr, this, IPLVector3.getCPtr(value), value);
  }

  public IPLVector3 getMaxCoordinates() {
    long cPtr = libphononJNI.IPLBox_maxCoordinates_get(swigCPtr, this);
    return (cPtr == 0) ? null : new IPLVector3(cPtr, false);
  }

  public IPLBox() {
    this(libphononJNI.new_IPLBox(), true);
  }

}
