/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class IPLBakedDataIdentifier {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected IPLBakedDataIdentifier(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IPLBakedDataIdentifier obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(IPLBakedDataIdentifier obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libphononJNI.delete_IPLBakedDataIdentifier(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setType(IPLBakedDataType value) {
    libphononJNI.IPLBakedDataIdentifier_type_set(swigCPtr, this, value.swigValue());
  }

  public IPLBakedDataType getType() {
    return IPLBakedDataType.swigToEnum(libphononJNI.IPLBakedDataIdentifier_type_get(swigCPtr, this));
  }

  public void setVariation(IPLBakedDataVariation value) {
    libphononJNI.IPLBakedDataIdentifier_variation_set(swigCPtr, this, value.swigValue());
  }

  public IPLBakedDataVariation getVariation() {
    return IPLBakedDataVariation.swigToEnum(libphononJNI.IPLBakedDataIdentifier_variation_get(swigCPtr, this));
  }

  public void setEndpointInfluence(IPLSphere value) {
    libphononJNI.IPLBakedDataIdentifier_endpointInfluence_set(swigCPtr, this, IPLSphere.getCPtr(value), value);
  }

  public IPLSphere getEndpointInfluence() {
    long cPtr = libphononJNI.IPLBakedDataIdentifier_endpointInfluence_get(swigCPtr, this);
    return (cPtr == 0) ? null : new IPLSphere(cPtr, false);
  }

  public IPLBakedDataIdentifier() {
    this(libphononJNI.new_IPLBakedDataIdentifier(), true);
  }

}
