/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class IPLbool {
  public final static IPLbool IPL_FALSE = new IPLbool("IPL_FALSE");
  public final static IPLbool IPL_TRUE = new IPLbool("IPL_TRUE");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static IPLbool swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + IPLbool.class + " with value " + swigValue);
  }

  private IPLbool(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private IPLbool(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private IPLbool(String swigName, IPLbool swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static IPLbool[] swigValues = { IPL_FALSE, IPL_TRUE };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

