/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class IPLContextSettings {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected IPLContextSettings(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IPLContextSettings obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(IPLContextSettings obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libphononJNI.delete_IPLContextSettings(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setVersion(long value) {
    libphononJNI.IPLContextSettings_version_set(swigCPtr, this, value);
  }

  public long getVersion() {
    return libphononJNI.IPLContextSettings_version_get(swigCPtr, this);
  }

  public void setLogCallback(SWIGTYPE_p_f_enum_IPLLogLevel_p_q_const__char__void value) {
    libphononJNI.IPLContextSettings_logCallback_set(swigCPtr, this, SWIGTYPE_p_f_enum_IPLLogLevel_p_q_const__char__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_enum_IPLLogLevel_p_q_const__char__void getLogCallback() {
    long cPtr = libphononJNI.IPLContextSettings_logCallback_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_enum_IPLLogLevel_p_q_const__char__void(cPtr, false);
  }

  public void setAllocateCallback(SWIGTYPE_p_f_size_t_size_t__p_void value) {
    libphononJNI.IPLContextSettings_allocateCallback_set(swigCPtr, this, SWIGTYPE_p_f_size_t_size_t__p_void.getCPtr(value));
  }

  public SWIGTYPE_p_f_size_t_size_t__p_void getAllocateCallback() {
    long cPtr = libphononJNI.IPLContextSettings_allocateCallback_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_size_t_size_t__p_void(cPtr, false);
  }

  public void setFreeCallback(SWIGTYPE_p_f_p_void__void value) {
    libphononJNI.IPLContextSettings_freeCallback_set(swigCPtr, this, SWIGTYPE_p_f_p_void__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_void__void getFreeCallback() {
    long cPtr = libphononJNI.IPLContextSettings_freeCallback_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_void__void(cPtr, false);
  }

  public void setSimdLevel(IPLSIMDLevel value) {
    libphononJNI.IPLContextSettings_simdLevel_set(swigCPtr, this, value.swigValue());
  }

  public IPLSIMDLevel getSimdLevel() {
    return IPLSIMDLevel.swigToEnum(libphononJNI.IPLContextSettings_simdLevel_get(swigCPtr, this));
  }

  public IPLContextSettings() {
    this(libphononJNI.new_IPLContextSettings(), true);
  }

}
