/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class IPLCoordinateSpace3 {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected IPLCoordinateSpace3(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IPLCoordinateSpace3 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(IPLCoordinateSpace3 obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libphononJNI.delete_IPLCoordinateSpace3(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setRight(IPLVector3 value) {
    libphononJNI.IPLCoordinateSpace3_right_set(swigCPtr, this, IPLVector3.getCPtr(value), value);
  }

  public IPLVector3 getRight() {
    long cPtr = libphononJNI.IPLCoordinateSpace3_right_get(swigCPtr, this);
    return (cPtr == 0) ? null : new IPLVector3(cPtr, false);
  }

  public void setUp(IPLVector3 value) {
    libphononJNI.IPLCoordinateSpace3_up_set(swigCPtr, this, IPLVector3.getCPtr(value), value);
  }

  public IPLVector3 getUp() {
    long cPtr = libphononJNI.IPLCoordinateSpace3_up_get(swigCPtr, this);
    return (cPtr == 0) ? null : new IPLVector3(cPtr, false);
  }

  public void setAhead(IPLVector3 value) {
    libphononJNI.IPLCoordinateSpace3_ahead_set(swigCPtr, this, IPLVector3.getCPtr(value), value);
  }

  public IPLVector3 getAhead() {
    long cPtr = libphononJNI.IPLCoordinateSpace3_ahead_get(swigCPtr, this);
    return (cPtr == 0) ? null : new IPLVector3(cPtr, false);
  }

  public void setOrigin(IPLVector3 value) {
    libphononJNI.IPLCoordinateSpace3_origin_set(swigCPtr, this, IPLVector3.getCPtr(value), value);
  }

  public IPLVector3 getOrigin() {
    long cPtr = libphononJNI.IPLCoordinateSpace3_origin_get(swigCPtr, this);
    return (cPtr == 0) ? null : new IPLVector3(cPtr, false);
  }

  public IPLCoordinateSpace3() {
    this(libphononJNI.new_IPLCoordinateSpace3(), true);
  }

}
