/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class IPLDirectivity {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected IPLDirectivity(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IPLDirectivity obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(IPLDirectivity obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libphononJNI.delete_IPLDirectivity(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setDipoleWeight(float value) {
    libphononJNI.IPLDirectivity_dipoleWeight_set(swigCPtr, this, value);
  }

  public float getDipoleWeight() {
    return libphononJNI.IPLDirectivity_dipoleWeight_get(swigCPtr, this);
  }

  public void setDipolePower(float value) {
    libphononJNI.IPLDirectivity_dipolePower_set(swigCPtr, this, value);
  }

  public float getDipolePower() {
    return libphononJNI.IPLDirectivity_dipolePower_get(swigCPtr, this);
  }

  public void setCallback(SWIGTYPE_p_f_IPLVector3_p_void__float value) {
    libphononJNI.IPLDirectivity_callback_set(swigCPtr, this, SWIGTYPE_p_f_IPLVector3_p_void__float.getCPtr(value));
  }

  public SWIGTYPE_p_f_IPLVector3_p_void__float getCallback() {
    long cPtr = libphononJNI.IPLDirectivity_callback_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_IPLVector3_p_void__float(cPtr, false);
  }

  public void setUserData(SWIGTYPE_p_void value) {
    libphononJNI.IPLDirectivity_userData_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getUserData() {
    long cPtr = libphononJNI.IPLDirectivity_userData_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public IPLDirectivity() {
    this(libphononJNI.new_IPLDirectivity(), true);
  }

}
