/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class IPLDirectEffectFlags {
  public final static IPLDirectEffectFlags IPL_DIRECTEFFECTFLAGS_APPLYDISTANCEATTENUATION = new IPLDirectEffectFlags("IPL_DIRECTEFFECTFLAGS_APPLYDISTANCEATTENUATION", libphononJNI.IPL_DIRECTEFFECTFLAGS_APPLYDISTANCEATTENUATION_get());
  public final static IPLDirectEffectFlags IPL_DIRECTEFFECTFLAGS_APPLYAIRABSORPTION = new IPLDirectEffectFlags("IPL_DIRECTEFFECTFLAGS_APPLYAIRABSORPTION", libphononJNI.IPL_DIRECTEFFECTFLAGS_APPLYAIRABSORPTION_get());
  public final static IPLDirectEffectFlags IPL_DIRECTEFFECTFLAGS_APPLYDIRECTIVITY = new IPLDirectEffectFlags("IPL_DIRECTEFFECTFLAGS_APPLYDIRECTIVITY", libphononJNI.IPL_DIRECTEFFECTFLAGS_APPLYDIRECTIVITY_get());
  public final static IPLDirectEffectFlags IPL_DIRECTEFFECTFLAGS_APPLYOCCLUSION = new IPLDirectEffectFlags("IPL_DIRECTEFFECTFLAGS_APPLYOCCLUSION", libphononJNI.IPL_DIRECTEFFECTFLAGS_APPLYOCCLUSION_get());
  public final static IPLDirectEffectFlags IPL_DIRECTEFFECTFLAGS_APPLYTRANSMISSION = new IPLDirectEffectFlags("IPL_DIRECTEFFECTFLAGS_APPLYTRANSMISSION", libphononJNI.IPL_DIRECTEFFECTFLAGS_APPLYTRANSMISSION_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static IPLDirectEffectFlags swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + IPLDirectEffectFlags.class + " with value " + swigValue);
  }

  private IPLDirectEffectFlags(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private IPLDirectEffectFlags(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private IPLDirectEffectFlags(String swigName, IPLDirectEffectFlags swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static IPLDirectEffectFlags[] swigValues = { IPL_DIRECTEFFECTFLAGS_APPLYDISTANCEATTENUATION, IPL_DIRECTEFFECTFLAGS_APPLYAIRABSORPTION, IPL_DIRECTEFFECTFLAGS_APPLYDIRECTIVITY, IPL_DIRECTEFFECTFLAGS_APPLYOCCLUSION, IPL_DIRECTEFFECTFLAGS_APPLYTRANSMISSION };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

