/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class IPLDistanceAttenuationModel {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected IPLDistanceAttenuationModel(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IPLDistanceAttenuationModel obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(IPLDistanceAttenuationModel obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libphononJNI.delete_IPLDistanceAttenuationModel(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setType(IPLDistanceAttenuationModelType value) {
    libphononJNI.IPLDistanceAttenuationModel_type_set(swigCPtr, this, value.swigValue());
  }

  public IPLDistanceAttenuationModelType getType() {
    return IPLDistanceAttenuationModelType.swigToEnum(libphononJNI.IPLDistanceAttenuationModel_type_get(swigCPtr, this));
  }

  public void setMinDistance(float value) {
    libphononJNI.IPLDistanceAttenuationModel_minDistance_set(swigCPtr, this, value);
  }

  public float getMinDistance() {
    return libphononJNI.IPLDistanceAttenuationModel_minDistance_get(swigCPtr, this);
  }

  public void setCallback(SWIGTYPE_p_f_float_p_void__float value) {
    libphononJNI.IPLDistanceAttenuationModel_callback_set(swigCPtr, this, SWIGTYPE_p_f_float_p_void__float.getCPtr(value));
  }

  public SWIGTYPE_p_f_float_p_void__float getCallback() {
    long cPtr = libphononJNI.IPLDistanceAttenuationModel_callback_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_float_p_void__float(cPtr, false);
  }

  public void setUserData(SWIGTYPE_p_void value) {
    libphononJNI.IPLDistanceAttenuationModel_userData_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getUserData() {
    long cPtr = libphononJNI.IPLDistanceAttenuationModel_userData_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void setDirty(IPLbool value) {
    libphononJNI.IPLDistanceAttenuationModel_dirty_set(swigCPtr, this, value.swigValue());
  }

  public IPLbool getDirty() {
    return IPLbool.swigToEnum(libphononJNI.IPLDistanceAttenuationModel_dirty_get(swigCPtr, this));
  }

  public IPLDistanceAttenuationModel() {
    this(libphononJNI.new_IPLDistanceAttenuationModel(), true);
  }

}
