/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class IPLDirectSimulationFlags {
  public final static IPLDirectSimulationFlags IPL_DIRECTSIMULATIONFLAGS_DISTANCEATTENUATION = new IPLDirectSimulationFlags("IPL_DIRECTSIMULATIONFLAGS_DISTANCEATTENUATION", libphononJNI.IPL_DIRECTSIMULATIONFLAGS_DISTANCEATTENUATION_get());
  public final static IPLDirectSimulationFlags IPL_DIRECTSIMULATIONFLAGS_AIRABSORPTION = new IPLDirectSimulationFlags("IPL_DIRECTSIMULATIONFLAGS_AIRABSORPTION", libphononJNI.IPL_DIRECTSIMULATIONFLAGS_AIRABSORPTION_get());
  public final static IPLDirectSimulationFlags IPL_DIRECTSIMULATIONFLAGS_DIRECTIVITY = new IPLDirectSimulationFlags("IPL_DIRECTSIMULATIONFLAGS_DIRECTIVITY", libphononJNI.IPL_DIRECTSIMULATIONFLAGS_DIRECTIVITY_get());
  public final static IPLDirectSimulationFlags IPL_DIRECTSIMULATIONFLAGS_OCCLUSION = new IPLDirectSimulationFlags("IPL_DIRECTSIMULATIONFLAGS_OCCLUSION", libphononJNI.IPL_DIRECTSIMULATIONFLAGS_OCCLUSION_get());
  public final static IPLDirectSimulationFlags IPL_DIRECTSIMULATIONFLAGS_TRANSMISSION = new IPLDirectSimulationFlags("IPL_DIRECTSIMULATIONFLAGS_TRANSMISSION", libphononJNI.IPL_DIRECTSIMULATIONFLAGS_TRANSMISSION_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static IPLDirectSimulationFlags swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + IPLDirectSimulationFlags.class + " with value " + swigValue);
  }

  private IPLDirectSimulationFlags(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private IPLDirectSimulationFlags(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private IPLDirectSimulationFlags(String swigName, IPLDirectSimulationFlags swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static IPLDirectSimulationFlags[] swigValues = { IPL_DIRECTSIMULATIONFLAGS_DISTANCEATTENUATION, IPL_DIRECTSIMULATIONFLAGS_AIRABSORPTION, IPL_DIRECTSIMULATIONFLAGS_DIRECTIVITY, IPL_DIRECTSIMULATIONFLAGS_OCCLUSION, IPL_DIRECTSIMULATIONFLAGS_TRANSMISSION };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

