/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class IPLDistanceAttenuationModelType {
  public final static IPLDistanceAttenuationModelType IPL_DISTANCEATTENUATIONTYPE_DEFAULT = new IPLDistanceAttenuationModelType("IPL_DISTANCEATTENUATIONTYPE_DEFAULT");
  public final static IPLDistanceAttenuationModelType IPL_DISTANCEATTENUATIONTYPE_INVERSEDISTANCE = new IPLDistanceAttenuationModelType("IPL_DISTANCEATTENUATIONTYPE_INVERSEDISTANCE");
  public final static IPLDistanceAttenuationModelType IPL_DISTANCEATTENUATIONTYPE_CALLBACK = new IPLDistanceAttenuationModelType("IPL_DISTANCEATTENUATIONTYPE_CALLBACK");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static IPLDistanceAttenuationModelType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + IPLDistanceAttenuationModelType.class + " with value " + swigValue);
  }

  private IPLDistanceAttenuationModelType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private IPLDistanceAttenuationModelType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private IPLDistanceAttenuationModelType(String swigName, IPLDistanceAttenuationModelType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static IPLDistanceAttenuationModelType[] swigValues = { IPL_DISTANCEATTENUATIONTYPE_DEFAULT, IPL_DISTANCEATTENUATIONTYPE_INVERSEDISTANCE, IPL_DISTANCEATTENUATIONTYPE_CALLBACK };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

