/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class IPLerror {
  public final static IPLerror IPL_STATUS_SUCCESS = new IPLerror("IPL_STATUS_SUCCESS");
  public final static IPLerror IPL_STATUS_FAILURE = new IPLerror("IPL_STATUS_FAILURE");
  public final static IPLerror IPL_STATUS_OUTOFMEMORY = new IPLerror("IPL_STATUS_OUTOFMEMORY");
  public final static IPLerror IPL_STATUS_INITIALIZATION = new IPLerror("IPL_STATUS_INITIALIZATION");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static IPLerror swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + IPLerror.class + " with value " + swigValue);
  }

  private IPLerror(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private IPLerror(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private IPLerror(String swigName, IPLerror swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static IPLerror[] swigValues = { IPL_STATUS_SUCCESS, IPL_STATUS_FAILURE, IPL_STATUS_OUTOFMEMORY, IPL_STATUS_INITIALIZATION };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

