/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class IPLHRTFNormType {
  public final static IPLHRTFNormType IPL_HRTFNORMTYPE_NONE = new IPLHRTFNormType("IPL_HRTFNORMTYPE_NONE");
  public final static IPLHRTFNormType IPL_HRTFNORMTYPE_RMS = new IPLHRTFNormType("IPL_HRTFNORMTYPE_RMS");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static IPLHRTFNormType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + IPLHRTFNormType.class + " with value " + swigValue);
  }

  private IPLHRTFNormType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private IPLHRTFNormType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private IPLHRTFNormType(String swigName, IPLHRTFNormType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static IPLHRTFNormType[] swigValues = { IPL_HRTFNORMTYPE_NONE, IPL_HRTFNORMTYPE_RMS };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

