/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class IPLHRTFSettings {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected IPLHRTFSettings(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IPLHRTFSettings obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(IPLHRTFSettings obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libphononJNI.delete_IPLHRTFSettings(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setType(IPLHRTFType value) {
    libphononJNI.IPLHRTFSettings_type_set(swigCPtr, this, value.swigValue());
  }

  public IPLHRTFType getType() {
    return IPLHRTFType.swigToEnum(libphononJNI.IPLHRTFSettings_type_get(swigCPtr, this));
  }

  public void setSofaFileName(String value) {
    libphononJNI.IPLHRTFSettings_sofaFileName_set(swigCPtr, this, value);
  }

  public String getSofaFileName() {
    return libphononJNI.IPLHRTFSettings_sofaFileName_get(swigCPtr, this);
  }

  public void setSofaData(SWIGTYPE_p_uint8_t value) {
    libphononJNI.IPLHRTFSettings_sofaData_set(swigCPtr, this, SWIGTYPE_p_uint8_t.getCPtr(value));
  }

  public SWIGTYPE_p_uint8_t getSofaData() {
    long cPtr = libphononJNI.IPLHRTFSettings_sofaData_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_uint8_t(cPtr, false);
  }

  public void setSofaDataSize(int value) {
    libphononJNI.IPLHRTFSettings_sofaDataSize_set(swigCPtr, this, value);
  }

  public int getSofaDataSize() {
    return libphononJNI.IPLHRTFSettings_sofaDataSize_get(swigCPtr, this);
  }

  public void setVolume(float value) {
    libphononJNI.IPLHRTFSettings_volume_set(swigCPtr, this, value);
  }

  public float getVolume() {
    return libphononJNI.IPLHRTFSettings_volume_get(swigCPtr, this);
  }

  public void setNormType(IPLHRTFNormType value) {
    libphononJNI.IPLHRTFSettings_normType_set(swigCPtr, this, value.swigValue());
  }

  public IPLHRTFNormType getNormType() {
    return IPLHRTFNormType.swigToEnum(libphononJNI.IPLHRTFSettings_normType_get(swigCPtr, this));
  }

  public IPLHRTFSettings() {
    this(libphononJNI.new_IPLHRTFSettings(), true);
  }

}
