/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class IPLHRTFType {
  public final static IPLHRTFType IPL_HRTFTYPE_DEFAULT = new IPLHRTFType("IPL_HRTFTYPE_DEFAULT");
  public final static IPLHRTFType IPL_HRTFTYPE_SOFA = new IPLHRTFType("IPL_HRTFTYPE_SOFA");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static IPLHRTFType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + IPLHRTFType.class + " with value " + swigValue);
  }

  private IPLHRTFType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private IPLHRTFType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private IPLHRTFType(String swigName, IPLHRTFType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static IPLHRTFType[] swigValues = { IPL_HRTFTYPE_DEFAULT, IPL_HRTFTYPE_SOFA };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

