/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class IPLHRTFInterpolation {
  public final static IPLHRTFInterpolation IPL_HRTFINTERPOLATION_NEAREST = new IPLHRTFInterpolation("IPL_HRTFINTERPOLATION_NEAREST");
  public final static IPLHRTFInterpolation IPL_HRTFINTERPOLATION_BILINEAR = new IPLHRTFInterpolation("IPL_HRTFINTERPOLATION_BILINEAR");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static IPLHRTFInterpolation swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + IPLHRTFInterpolation.class + " with value " + swigValue);
  }

  private IPLHRTFInterpolation(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private IPLHRTFInterpolation(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private IPLHRTFInterpolation(String swigName, IPLHRTFInterpolation swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static IPLHRTFInterpolation[] swigValues = { IPL_HRTFINTERPOLATION_NEAREST, IPL_HRTFINTERPOLATION_BILINEAR };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

