/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class IPLInstancedMeshSettings {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected IPLInstancedMeshSettings(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IPLInstancedMeshSettings obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(IPLInstancedMeshSettings obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libphononJNI.delete_IPLInstancedMeshSettings(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setSubScene(SWIGTYPE_p__IPLScene_t value) {
    libphononJNI.IPLInstancedMeshSettings_subScene_set(swigCPtr, this, SWIGTYPE_p__IPLScene_t.getCPtr(value));
  }

  public SWIGTYPE_p__IPLScene_t getSubScene() {
    long cPtr = libphononJNI.IPLInstancedMeshSettings_subScene_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p__IPLScene_t(cPtr, false);
  }

  public void setTransform(IPLMatrix4x4 value) {
    libphononJNI.IPLInstancedMeshSettings_transform_set(swigCPtr, this, IPLMatrix4x4.getCPtr(value), value);
  }

  public IPLMatrix4x4 getTransform() {
    long cPtr = libphononJNI.IPLInstancedMeshSettings_transform_get(swigCPtr, this);
    return (cPtr == 0) ? null : new IPLMatrix4x4(cPtr, false);
  }

  public IPLInstancedMeshSettings() {
    this(libphononJNI.new_IPLInstancedMeshSettings(), true);
  }

}
