/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class IPLLogLevel {
  public final static IPLLogLevel IPL_LOGLEVEL_INFO = new IPLLogLevel("IPL_LOGLEVEL_INFO");
  public final static IPLLogLevel IPL_LOGLEVEL_WARNING = new IPLLogLevel("IPL_LOGLEVEL_WARNING");
  public final static IPLLogLevel IPL_LOGLEVEL_ERROR = new IPLLogLevel("IPL_LOGLEVEL_ERROR");
  public final static IPLLogLevel IPL_LOGLEVEL_DEBUG = new IPLLogLevel("IPL_LOGLEVEL_DEBUG");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static IPLLogLevel swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + IPLLogLevel.class + " with value " + swigValue);
  }

  private IPLLogLevel(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private IPLLogLevel(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private IPLLogLevel(String swigName, IPLLogLevel swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static IPLLogLevel[] swigValues = { IPL_LOGLEVEL_INFO, IPL_LOGLEVEL_WARNING, IPL_LOGLEVEL_ERROR, IPL_LOGLEVEL_DEBUG };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

