/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class IPLMaterial {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected IPLMaterial(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IPLMaterial obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(IPLMaterial obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libphononJNI.delete_IPLMaterial(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setAbsorption(SWIGTYPE_p_float value) {
    libphononJNI.IPLMaterial_absorption_set(swigCPtr, this, SWIGTYPE_p_float.getCPtr(value));
  }

  public SWIGTYPE_p_float getAbsorption() {
    long cPtr = libphononJNI.IPLMaterial_absorption_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_float(cPtr, false);
  }

  public void setScattering(float value) {
    libphononJNI.IPLMaterial_scattering_set(swigCPtr, this, value);
  }

  public float getScattering() {
    return libphononJNI.IPLMaterial_scattering_get(swigCPtr, this);
  }

  public void setTransmission(SWIGTYPE_p_float value) {
    libphononJNI.IPLMaterial_transmission_set(swigCPtr, this, SWIGTYPE_p_float.getCPtr(value));
  }

  public SWIGTYPE_p_float getTransmission() {
    long cPtr = libphononJNI.IPLMaterial_transmission_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_float(cPtr, false);
  }

  public IPLMaterial() {
    this(libphononJNI.new_IPLMaterial(), true);
  }

}
