/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class IPLMatrix4x4 {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected IPLMatrix4x4(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IPLMatrix4x4 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(IPLMatrix4x4 obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libphononJNI.delete_IPLMatrix4x4(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setElements(SWIGTYPE_p_a_4__float value) {
    libphononJNI.IPLMatrix4x4_elements_set(swigCPtr, this, SWIGTYPE_p_a_4__float.getCPtr(value));
  }

  public SWIGTYPE_p_a_4__float getElements() {
    long cPtr = libphononJNI.IPLMatrix4x4_elements_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_4__float(cPtr, false);
  }

  public IPLMatrix4x4() {
    this(libphononJNI.new_IPLMatrix4x4(), true);
  }

}
