/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class IPLOpenCLDeviceType {
  public final static IPLOpenCLDeviceType IPL_OPENCLDEVICETYPE_ANY = new IPLOpenCLDeviceType("IPL_OPENCLDEVICETYPE_ANY");
  public final static IPLOpenCLDeviceType IPL_OPENCLDEVICETYPE_CPU = new IPLOpenCLDeviceType("IPL_OPENCLDEVICETYPE_CPU");
  public final static IPLOpenCLDeviceType IPL_OPENCLDEVICETYPE_GPU = new IPLOpenCLDeviceType("IPL_OPENCLDEVICETYPE_GPU");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static IPLOpenCLDeviceType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + IPLOpenCLDeviceType.class + " with value " + swigValue);
  }

  private IPLOpenCLDeviceType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private IPLOpenCLDeviceType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private IPLOpenCLDeviceType(String swigName, IPLOpenCLDeviceType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static IPLOpenCLDeviceType[] swigValues = { IPL_OPENCLDEVICETYPE_ANY, IPL_OPENCLDEVICETYPE_CPU, IPL_OPENCLDEVICETYPE_GPU };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

