/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class IPLOpenCLDeviceSettings {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected IPLOpenCLDeviceSettings(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IPLOpenCLDeviceSettings obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(IPLOpenCLDeviceSettings obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libphononJNI.delete_IPLOpenCLDeviceSettings(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setType(IPLOpenCLDeviceType value) {
    libphononJNI.IPLOpenCLDeviceSettings_type_set(swigCPtr, this, value.swigValue());
  }

  public IPLOpenCLDeviceType getType() {
    return IPLOpenCLDeviceType.swigToEnum(libphononJNI.IPLOpenCLDeviceSettings_type_get(swigCPtr, this));
  }

  public void setNumCUsToReserve(int value) {
    libphononJNI.IPLOpenCLDeviceSettings_numCUsToReserve_set(swigCPtr, this, value);
  }

  public int getNumCUsToReserve() {
    return libphononJNI.IPLOpenCLDeviceSettings_numCUsToReserve_get(swigCPtr, this);
  }

  public void setFractionCUsForIRUpdate(float value) {
    libphononJNI.IPLOpenCLDeviceSettings_fractionCUsForIRUpdate_set(swigCPtr, this, value);
  }

  public float getFractionCUsForIRUpdate() {
    return libphononJNI.IPLOpenCLDeviceSettings_fractionCUsForIRUpdate_get(swigCPtr, this);
  }

  public void setRequiresTAN(IPLbool value) {
    libphononJNI.IPLOpenCLDeviceSettings_requiresTAN_set(swigCPtr, this, value.swigValue());
  }

  public IPLbool getRequiresTAN() {
    return IPLbool.swigToEnum(libphononJNI.IPLOpenCLDeviceSettings_requiresTAN_get(swigCPtr, this));
  }

  public IPLOpenCLDeviceSettings() {
    this(libphononJNI.new_IPLOpenCLDeviceSettings(), true);
  }

}
