/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class IPLOcclusionType {
  public final static IPLOcclusionType IPL_OCCLUSIONTYPE_RAYCAST = new IPLOcclusionType("IPL_OCCLUSIONTYPE_RAYCAST");
  public final static IPLOcclusionType IPL_OCCLUSIONTYPE_VOLUMETRIC = new IPLOcclusionType("IPL_OCCLUSIONTYPE_VOLUMETRIC");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static IPLOcclusionType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + IPLOcclusionType.class + " with value " + swigValue);
  }

  private IPLOcclusionType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private IPLOcclusionType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private IPLOcclusionType(String swigName, IPLOcclusionType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static IPLOcclusionType[] swigValues = { IPL_OCCLUSIONTYPE_RAYCAST, IPL_OCCLUSIONTYPE_VOLUMETRIC };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

