/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class IPLOpenCLDeviceDesc {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected IPLOpenCLDeviceDesc(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IPLOpenCLDeviceDesc obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(IPLOpenCLDeviceDesc obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libphononJNI.delete_IPLOpenCLDeviceDesc(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setPlatform(SWIGTYPE_p_void value) {
    libphononJNI.IPLOpenCLDeviceDesc_platform_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getPlatform() {
    long cPtr = libphononJNI.IPLOpenCLDeviceDesc_platform_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void setPlatformName(String value) {
    libphononJNI.IPLOpenCLDeviceDesc_platformName_set(swigCPtr, this, value);
  }

  public String getPlatformName() {
    return libphononJNI.IPLOpenCLDeviceDesc_platformName_get(swigCPtr, this);
  }

  public void setPlatformVendor(String value) {
    libphononJNI.IPLOpenCLDeviceDesc_platformVendor_set(swigCPtr, this, value);
  }

  public String getPlatformVendor() {
    return libphononJNI.IPLOpenCLDeviceDesc_platformVendor_get(swigCPtr, this);
  }

  public void setPlatformVersion(String value) {
    libphononJNI.IPLOpenCLDeviceDesc_platformVersion_set(swigCPtr, this, value);
  }

  public String getPlatformVersion() {
    return libphononJNI.IPLOpenCLDeviceDesc_platformVersion_get(swigCPtr, this);
  }

  public void setDevice(SWIGTYPE_p_void value) {
    libphononJNI.IPLOpenCLDeviceDesc_device_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getDevice() {
    long cPtr = libphononJNI.IPLOpenCLDeviceDesc_device_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void setDeviceName(String value) {
    libphononJNI.IPLOpenCLDeviceDesc_deviceName_set(swigCPtr, this, value);
  }

  public String getDeviceName() {
    return libphononJNI.IPLOpenCLDeviceDesc_deviceName_get(swigCPtr, this);
  }

  public void setDeviceVendor(String value) {
    libphononJNI.IPLOpenCLDeviceDesc_deviceVendor_set(swigCPtr, this, value);
  }

  public String getDeviceVendor() {
    return libphononJNI.IPLOpenCLDeviceDesc_deviceVendor_get(swigCPtr, this);
  }

  public void setDeviceVersion(String value) {
    libphononJNI.IPLOpenCLDeviceDesc_deviceVersion_set(swigCPtr, this, value);
  }

  public String getDeviceVersion() {
    return libphononJNI.IPLOpenCLDeviceDesc_deviceVersion_get(swigCPtr, this);
  }

  public void setType(IPLOpenCLDeviceType value) {
    libphononJNI.IPLOpenCLDeviceDesc_type_set(swigCPtr, this, value.swigValue());
  }

  public IPLOpenCLDeviceType getType() {
    return IPLOpenCLDeviceType.swigToEnum(libphononJNI.IPLOpenCLDeviceDesc_type_get(swigCPtr, this));
  }

  public void setNumConvolutionCUs(int value) {
    libphononJNI.IPLOpenCLDeviceDesc_numConvolutionCUs_set(swigCPtr, this, value);
  }

  public int getNumConvolutionCUs() {
    return libphononJNI.IPLOpenCLDeviceDesc_numConvolutionCUs_get(swigCPtr, this);
  }

  public void setNumIRUpdateCUs(int value) {
    libphononJNI.IPLOpenCLDeviceDesc_numIRUpdateCUs_set(swigCPtr, this, value);
  }

  public int getNumIRUpdateCUs() {
    return libphononJNI.IPLOpenCLDeviceDesc_numIRUpdateCUs_get(swigCPtr, this);
  }

  public void setGranularity(int value) {
    libphononJNI.IPLOpenCLDeviceDesc_granularity_set(swigCPtr, this, value);
  }

  public int getGranularity() {
    return libphononJNI.IPLOpenCLDeviceDesc_granularity_get(swigCPtr, this);
  }

  public void setPerfScore(float value) {
    libphononJNI.IPLOpenCLDeviceDesc_perfScore_set(swigCPtr, this, value);
  }

  public float getPerfScore() {
    return libphononJNI.IPLOpenCLDeviceDesc_perfScore_get(swigCPtr, this);
  }

  public IPLOpenCLDeviceDesc() {
    this(libphononJNI.new_IPLOpenCLDeviceDesc(), true);
  }

}
