/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class IPLPanningEffectSettings {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected IPLPanningEffectSettings(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IPLPanningEffectSettings obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(IPLPanningEffectSettings obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libphononJNI.delete_IPLPanningEffectSettings(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setSpeakerLayout(IPLSpeakerLayout value) {
    libphononJNI.IPLPanningEffectSettings_speakerLayout_set(swigCPtr, this, IPLSpeakerLayout.getCPtr(value), value);
  }

  public IPLSpeakerLayout getSpeakerLayout() {
    long cPtr = libphononJNI.IPLPanningEffectSettings_speakerLayout_get(swigCPtr, this);
    return (cPtr == 0) ? null : new IPLSpeakerLayout(cPtr, false);
  }

  public IPLPanningEffectSettings() {
    this(libphononJNI.new_IPLPanningEffectSettings(), true);
  }

}
