/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class IPLProbeGenerationParams {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected IPLProbeGenerationParams(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IPLProbeGenerationParams obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(IPLProbeGenerationParams obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libphononJNI.delete_IPLProbeGenerationParams(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setType(IPLProbeGenerationType value) {
    libphononJNI.IPLProbeGenerationParams_type_set(swigCPtr, this, value.swigValue());
  }

  public IPLProbeGenerationType getType() {
    return IPLProbeGenerationType.swigToEnum(libphononJNI.IPLProbeGenerationParams_type_get(swigCPtr, this));
  }

  public void setSpacing(float value) {
    libphononJNI.IPLProbeGenerationParams_spacing_set(swigCPtr, this, value);
  }

  public float getSpacing() {
    return libphononJNI.IPLProbeGenerationParams_spacing_get(swigCPtr, this);
  }

  public void setHeight(float value) {
    libphononJNI.IPLProbeGenerationParams_height_set(swigCPtr, this, value);
  }

  public float getHeight() {
    return libphononJNI.IPLProbeGenerationParams_height_get(swigCPtr, this);
  }

  public void setTransform(IPLMatrix4x4 value) {
    libphononJNI.IPLProbeGenerationParams_transform_set(swigCPtr, this, IPLMatrix4x4.getCPtr(value), value);
  }

  public IPLMatrix4x4 getTransform() {
    long cPtr = libphononJNI.IPLProbeGenerationParams_transform_get(swigCPtr, this);
    return (cPtr == 0) ? null : new IPLMatrix4x4(cPtr, false);
  }

  public IPLProbeGenerationParams() {
    this(libphononJNI.new_IPLProbeGenerationParams(), true);
  }

}
