/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class IPLProbeGenerationType {
  public final static IPLProbeGenerationType IPL_PROBEGENERATIONTYPE_CENTROID = new IPLProbeGenerationType("IPL_PROBEGENERATIONTYPE_CENTROID");
  public final static IPLProbeGenerationType IPL_PROBEGENERATIONTYPE_UNIFORMFLOOR = new IPLProbeGenerationType("IPL_PROBEGENERATIONTYPE_UNIFORMFLOOR");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static IPLProbeGenerationType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + IPLProbeGenerationType.class + " with value " + swigValue);
  }

  private IPLProbeGenerationType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private IPLProbeGenerationType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private IPLProbeGenerationType(String swigName, IPLProbeGenerationType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static IPLProbeGenerationType[] swigValues = { IPL_PROBEGENERATIONTYPE_CENTROID, IPL_PROBEGENERATIONTYPE_UNIFORMFLOOR };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

