/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class IPLReflectionEffectType {
  public final static IPLReflectionEffectType IPL_REFLECTIONEFFECTTYPE_CONVOLUTION = new IPLReflectionEffectType("IPL_REFLECTIONEFFECTTYPE_CONVOLUTION");
  public final static IPLReflectionEffectType IPL_REFLECTIONEFFECTTYPE_PARAMETRIC = new IPLReflectionEffectType("IPL_REFLECTIONEFFECTTYPE_PARAMETRIC");
  public final static IPLReflectionEffectType IPL_REFLECTIONEFFECTTYPE_HYBRID = new IPLReflectionEffectType("IPL_REFLECTIONEFFECTTYPE_HYBRID");
  public final static IPLReflectionEffectType IPL_REFLECTIONEFFECTTYPE_TAN = new IPLReflectionEffectType("IPL_REFLECTIONEFFECTTYPE_TAN");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static IPLReflectionEffectType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + IPLReflectionEffectType.class + " with value " + swigValue);
  }

  private IPLReflectionEffectType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private IPLReflectionEffectType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private IPLReflectionEffectType(String swigName, IPLReflectionEffectType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static IPLReflectionEffectType[] swigValues = { IPL_REFLECTIONEFFECTTYPE_CONVOLUTION, IPL_REFLECTIONEFFECTTYPE_PARAMETRIC, IPL_REFLECTIONEFFECTTYPE_HYBRID, IPL_REFLECTIONEFFECTTYPE_TAN };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

