/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class IPLRay {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected IPLRay(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IPLRay obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(IPLRay obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libphononJNI.delete_IPLRay(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setOrigin(IPLVector3 value) {
    libphononJNI.IPLRay_origin_set(swigCPtr, this, IPLVector3.getCPtr(value), value);
  }

  public IPLVector3 getOrigin() {
    long cPtr = libphononJNI.IPLRay_origin_get(swigCPtr, this);
    return (cPtr == 0) ? null : new IPLVector3(cPtr, false);
  }

  public void setDirection(IPLVector3 value) {
    libphononJNI.IPLRay_direction_set(swigCPtr, this, IPLVector3.getCPtr(value), value);
  }

  public IPLVector3 getDirection() {
    long cPtr = libphononJNI.IPLRay_direction_get(swigCPtr, this);
    return (cPtr == 0) ? null : new IPLVector3(cPtr, false);
  }

  public IPLRay() {
    this(libphononJNI.new_IPLRay(), true);
  }

}
