/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class IPLReflectionEffectSettings {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected IPLReflectionEffectSettings(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IPLReflectionEffectSettings obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(IPLReflectionEffectSettings obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libphononJNI.delete_IPLReflectionEffectSettings(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setType(IPLReflectionEffectType value) {
    libphononJNI.IPLReflectionEffectSettings_type_set(swigCPtr, this, value.swigValue());
  }

  public IPLReflectionEffectType getType() {
    return IPLReflectionEffectType.swigToEnum(libphononJNI.IPLReflectionEffectSettings_type_get(swigCPtr, this));
  }

  public void setIrSize(int value) {
    libphononJNI.IPLReflectionEffectSettings_irSize_set(swigCPtr, this, value);
  }

  public int getIrSize() {
    return libphononJNI.IPLReflectionEffectSettings_irSize_get(swigCPtr, this);
  }

  public void setNumChannels(int value) {
    libphononJNI.IPLReflectionEffectSettings_numChannels_set(swigCPtr, this, value);
  }

  public int getNumChannels() {
    return libphononJNI.IPLReflectionEffectSettings_numChannels_get(swigCPtr, this);
  }

  public IPLReflectionEffectSettings() {
    this(libphononJNI.new_IPLReflectionEffectSettings(), true);
  }

}
