/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class IPLSimulationOutputs {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected IPLSimulationOutputs(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IPLSimulationOutputs obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(IPLSimulationOutputs obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libphononJNI.delete_IPLSimulationOutputs(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setDirect(IPLDirectEffectParams value) {
    libphononJNI.IPLSimulationOutputs_direct_set(swigCPtr, this, IPLDirectEffectParams.getCPtr(value), value);
  }

  public IPLDirectEffectParams getDirect() {
    long cPtr = libphononJNI.IPLSimulationOutputs_direct_get(swigCPtr, this);
    return (cPtr == 0) ? null : new IPLDirectEffectParams(cPtr, false);
  }

  public void setReflections(IPLReflectionEffectParams value) {
    libphononJNI.IPLSimulationOutputs_reflections_set(swigCPtr, this, IPLReflectionEffectParams.getCPtr(value), value);
  }

  public IPLReflectionEffectParams getReflections() {
    long cPtr = libphononJNI.IPLSimulationOutputs_reflections_get(swigCPtr, this);
    return (cPtr == 0) ? null : new IPLReflectionEffectParams(cPtr, false);
  }

  public void setPathing(IPLPathEffectParams value) {
    libphononJNI.IPLSimulationOutputs_pathing_set(swigCPtr, this, IPLPathEffectParams.getCPtr(value), value);
  }

  public IPLPathEffectParams getPathing() {
    long cPtr = libphononJNI.IPLSimulationOutputs_pathing_get(swigCPtr, this);
    return (cPtr == 0) ? null : new IPLPathEffectParams(cPtr, false);
  }

  public IPLSimulationOutputs() {
    this(libphononJNI.new_IPLSimulationOutputs(), true);
  }

}
