/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class IPLSIMDLevel {
  public final static IPLSIMDLevel IPL_SIMDLEVEL_SSE2 = new IPLSIMDLevel("IPL_SIMDLEVEL_SSE2");
  public final static IPLSIMDLevel IPL_SIMDLEVEL_SSE4 = new IPLSIMDLevel("IPL_SIMDLEVEL_SSE4");
  public final static IPLSIMDLevel IPL_SIMDLEVEL_AVX = new IPLSIMDLevel("IPL_SIMDLEVEL_AVX");
  public final static IPLSIMDLevel IPL_SIMDLEVEL_AVX2 = new IPLSIMDLevel("IPL_SIMDLEVEL_AVX2");
  public final static IPLSIMDLevel IPL_SIMDLEVEL_AVX512 = new IPLSIMDLevel("IPL_SIMDLEVEL_AVX512");
  public final static IPLSIMDLevel IPL_SIMDLEVEL_NEON = new IPLSIMDLevel("IPL_SIMDLEVEL_NEON", libphononJNI.IPL_SIMDLEVEL_NEON_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static IPLSIMDLevel swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + IPLSIMDLevel.class + " with value " + swigValue);
  }

  private IPLSIMDLevel(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private IPLSIMDLevel(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private IPLSIMDLevel(String swigName, IPLSIMDLevel swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static IPLSIMDLevel[] swigValues = { IPL_SIMDLEVEL_SSE2, IPL_SIMDLEVEL_SSE4, IPL_SIMDLEVEL_AVX, IPL_SIMDLEVEL_AVX2, IPL_SIMDLEVEL_AVX512, IPL_SIMDLEVEL_NEON };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

