/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class IPLSourceSettings {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected IPLSourceSettings(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IPLSourceSettings obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(IPLSourceSettings obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libphononJNI.delete_IPLSourceSettings(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setFlags(IPLSimulationFlags value) {
    libphononJNI.IPLSourceSettings_flags_set(swigCPtr, this, value.swigValue());
  }

  public IPLSimulationFlags getFlags() {
    return IPLSimulationFlags.swigToEnum(libphononJNI.IPLSourceSettings_flags_get(swigCPtr, this));
  }

  public IPLSourceSettings() {
    this(libphononJNI.new_IPLSourceSettings(), true);
  }

}
