/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class IPLSphere {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected IPLSphere(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IPLSphere obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(IPLSphere obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libphononJNI.delete_IPLSphere(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCenter(IPLVector3 value) {
    libphononJNI.IPLSphere_center_set(swigCPtr, this, IPLVector3.getCPtr(value), value);
  }

  public IPLVector3 getCenter() {
    long cPtr = libphononJNI.IPLSphere_center_get(swigCPtr, this);
    return (cPtr == 0) ? null : new IPLVector3(cPtr, false);
  }

  public void setRadius(float value) {
    libphononJNI.IPLSphere_radius_set(swigCPtr, this, value);
  }

  public float getRadius() {
    return libphononJNI.IPLSphere_radius_get(swigCPtr, this);
  }

  public IPLSphere() {
    this(libphononJNI.new_IPLSphere(), true);
  }

}
