/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class IPLSimulationFlags {
  public final static IPLSimulationFlags IPL_SIMULATIONFLAGS_DIRECT = new IPLSimulationFlags("IPL_SIMULATIONFLAGS_DIRECT", libphononJNI.IPL_SIMULATIONFLAGS_DIRECT_get());
  public final static IPLSimulationFlags IPL_SIMULATIONFLAGS_REFLECTIONS = new IPLSimulationFlags("IPL_SIMULATIONFLAGS_REFLECTIONS", libphononJNI.IPL_SIMULATIONFLAGS_REFLECTIONS_get());
  public final static IPLSimulationFlags IPL_SIMULATIONFLAGS_PATHING = new IPLSimulationFlags("IPL_SIMULATIONFLAGS_PATHING", libphononJNI.IPL_SIMULATIONFLAGS_PATHING_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static IPLSimulationFlags swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + IPLSimulationFlags.class + " with value " + swigValue);
  }

  private IPLSimulationFlags(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private IPLSimulationFlags(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private IPLSimulationFlags(String swigName, IPLSimulationFlags swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static IPLSimulationFlags[] swigValues = { IPL_SIMULATIONFLAGS_DIRECT, IPL_SIMULATIONFLAGS_REFLECTIONS, IPL_SIMULATIONFLAGS_PATHING };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

