/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class IPLSceneSettings {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected IPLSceneSettings(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IPLSceneSettings obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(IPLSceneSettings obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libphononJNI.delete_IPLSceneSettings(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setType(IPLSceneType value) {
    libphononJNI.IPLSceneSettings_type_set(swigCPtr, this, value.swigValue());
  }

  public IPLSceneType getType() {
    return IPLSceneType.swigToEnum(libphononJNI.IPLSceneSettings_type_get(swigCPtr, this));
  }

  public void setClosestHitCallback(SWIGTYPE_p_f_p_q_const__IPLRay_float_float_p_IPLHit_p_void__void value) {
    libphononJNI.IPLSceneSettings_closestHitCallback_set(swigCPtr, this, SWIGTYPE_p_f_p_q_const__IPLRay_float_float_p_IPLHit_p_void__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_q_const__IPLRay_float_float_p_IPLHit_p_void__void getClosestHitCallback() {
    long cPtr = libphononJNI.IPLSceneSettings_closestHitCallback_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_q_const__IPLRay_float_float_p_IPLHit_p_void__void(cPtr, false);
  }

  public void setAnyHitCallback(SWIGTYPE_p_f_p_q_const__IPLRay_float_float_p_unsigned_char_p_void__void value) {
    libphononJNI.IPLSceneSettings_anyHitCallback_set(swigCPtr, this, SWIGTYPE_p_f_p_q_const__IPLRay_float_float_p_unsigned_char_p_void__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_q_const__IPLRay_float_float_p_unsigned_char_p_void__void getAnyHitCallback() {
    long cPtr = libphononJNI.IPLSceneSettings_anyHitCallback_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_q_const__IPLRay_float_float_p_unsigned_char_p_void__void(cPtr, false);
  }

  public void setBatchedClosestHitCallback(SWIGTYPE_p_f_int_p_q_const__IPLRay_p_q_const__float_p_q_const__float_p_IPLHit_p_void__void value) {
    libphononJNI.IPLSceneSettings_batchedClosestHitCallback_set(swigCPtr, this, SWIGTYPE_p_f_int_p_q_const__IPLRay_p_q_const__float_p_q_const__float_p_IPLHit_p_void__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_int_p_q_const__IPLRay_p_q_const__float_p_q_const__float_p_IPLHit_p_void__void getBatchedClosestHitCallback() {
    long cPtr = libphononJNI.IPLSceneSettings_batchedClosestHitCallback_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_int_p_q_const__IPLRay_p_q_const__float_p_q_const__float_p_IPLHit_p_void__void(cPtr, false);
  }

  public void setBatchedAnyHitCallback(SWIGTYPE_p_f_int_p_q_const__IPLRay_p_q_const__float_p_q_const__float_p_unsigned_char_p_void__void value) {
    libphononJNI.IPLSceneSettings_batchedAnyHitCallback_set(swigCPtr, this, SWIGTYPE_p_f_int_p_q_const__IPLRay_p_q_const__float_p_q_const__float_p_unsigned_char_p_void__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_int_p_q_const__IPLRay_p_q_const__float_p_q_const__float_p_unsigned_char_p_void__void getBatchedAnyHitCallback() {
    long cPtr = libphononJNI.IPLSceneSettings_batchedAnyHitCallback_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_int_p_q_const__IPLRay_p_q_const__float_p_q_const__float_p_unsigned_char_p_void__void(cPtr, false);
  }

  public void setUserData(SWIGTYPE_p_void value) {
    libphononJNI.IPLSceneSettings_userData_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getUserData() {
    long cPtr = libphononJNI.IPLSceneSettings_userData_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void setEmbreeDevice(SWIGTYPE_p__IPLEmbreeDevice_t value) {
    libphononJNI.IPLSceneSettings_embreeDevice_set(swigCPtr, this, SWIGTYPE_p__IPLEmbreeDevice_t.getCPtr(value));
  }

  public SWIGTYPE_p__IPLEmbreeDevice_t getEmbreeDevice() {
    long cPtr = libphononJNI.IPLSceneSettings_embreeDevice_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p__IPLEmbreeDevice_t(cPtr, false);
  }

  public void setRadeonRaysDevice(SWIGTYPE_p__IPLRadeonRaysDevice_t value) {
    libphononJNI.IPLSceneSettings_radeonRaysDevice_set(swigCPtr, this, SWIGTYPE_p__IPLRadeonRaysDevice_t.getCPtr(value));
  }

  public SWIGTYPE_p__IPLRadeonRaysDevice_t getRadeonRaysDevice() {
    long cPtr = libphononJNI.IPLSceneSettings_radeonRaysDevice_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p__IPLRadeonRaysDevice_t(cPtr, false);
  }

  public IPLSceneSettings() {
    this(libphononJNI.new_IPLSceneSettings(), true);
  }

}
