/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class IPLSpeakerLayoutType {
  public final static IPLSpeakerLayoutType IPL_SPEAKERLAYOUTTYPE_MONO = new IPLSpeakerLayoutType("IPL_SPEAKERLAYOUTTYPE_MONO");
  public final static IPLSpeakerLayoutType IPL_SPEAKERLAYOUTTYPE_STEREO = new IPLSpeakerLayoutType("IPL_SPEAKERLAYOUTTYPE_STEREO");
  public final static IPLSpeakerLayoutType IPL_SPEAKERLAYOUTTYPE_QUADRAPHONIC = new IPLSpeakerLayoutType("IPL_SPEAKERLAYOUTTYPE_QUADRAPHONIC");
  public final static IPLSpeakerLayoutType IPL_SPEAKERLAYOUTTYPE_SURROUND_5_1 = new IPLSpeakerLayoutType("IPL_SPEAKERLAYOUTTYPE_SURROUND_5_1");
  public final static IPLSpeakerLayoutType IPL_SPEAKERLAYOUTTYPE_SURROUND_7_1 = new IPLSpeakerLayoutType("IPL_SPEAKERLAYOUTTYPE_SURROUND_7_1");
  public final static IPLSpeakerLayoutType IPL_SPEAKERLAYOUTTYPE_CUSTOM = new IPLSpeakerLayoutType("IPL_SPEAKERLAYOUTTYPE_CUSTOM");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static IPLSpeakerLayoutType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + IPLSpeakerLayoutType.class + " with value " + swigValue);
  }

  private IPLSpeakerLayoutType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private IPLSpeakerLayoutType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private IPLSpeakerLayoutType(String swigName, IPLSpeakerLayoutType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static IPLSpeakerLayoutType[] swigValues = { IPL_SPEAKERLAYOUTTYPE_MONO, IPL_SPEAKERLAYOUTTYPE_STEREO, IPL_SPEAKERLAYOUTTYPE_QUADRAPHONIC, IPL_SPEAKERLAYOUTTYPE_SURROUND_5_1, IPL_SPEAKERLAYOUTTYPE_SURROUND_7_1, IPL_SPEAKERLAYOUTTYPE_CUSTOM };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

