/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class IPLStaticMeshSettings {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected IPLStaticMeshSettings(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IPLStaticMeshSettings obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(IPLStaticMeshSettings obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libphononJNI.delete_IPLStaticMeshSettings(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setNumVertices(int value) {
    libphononJNI.IPLStaticMeshSettings_numVertices_set(swigCPtr, this, value);
  }

  public int getNumVertices() {
    return libphononJNI.IPLStaticMeshSettings_numVertices_get(swigCPtr, this);
  }

  public void setNumTriangles(int value) {
    libphononJNI.IPLStaticMeshSettings_numTriangles_set(swigCPtr, this, value);
  }

  public int getNumTriangles() {
    return libphononJNI.IPLStaticMeshSettings_numTriangles_get(swigCPtr, this);
  }

  public void setNumMaterials(int value) {
    libphononJNI.IPLStaticMeshSettings_numMaterials_set(swigCPtr, this, value);
  }

  public int getNumMaterials() {
    return libphononJNI.IPLStaticMeshSettings_numMaterials_get(swigCPtr, this);
  }

  public void setVertices(IPLVector3 value) {
    libphononJNI.IPLStaticMeshSettings_vertices_set(swigCPtr, this, IPLVector3.getCPtr(value), value);
  }

  public IPLVector3 getVertices() {
    long cPtr = libphononJNI.IPLStaticMeshSettings_vertices_get(swigCPtr, this);
    return (cPtr == 0) ? null : new IPLVector3(cPtr, false);
  }

  public void setTriangles(IPLTriangle value) {
    libphononJNI.IPLStaticMeshSettings_triangles_set(swigCPtr, this, IPLTriangle.getCPtr(value), value);
  }

  public IPLTriangle getTriangles() {
    long cPtr = libphononJNI.IPLStaticMeshSettings_triangles_get(swigCPtr, this);
    return (cPtr == 0) ? null : new IPLTriangle(cPtr, false);
  }

  public void setMaterialIndices(SWIGTYPE_p_int value) {
    libphononJNI.IPLStaticMeshSettings_materialIndices_set(swigCPtr, this, SWIGTYPE_p_int.getCPtr(value));
  }

  public SWIGTYPE_p_int getMaterialIndices() {
    long cPtr = libphononJNI.IPLStaticMeshSettings_materialIndices_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public void setMaterials(IPLMaterial value) {
    libphononJNI.IPLStaticMeshSettings_materials_set(swigCPtr, this, IPLMaterial.getCPtr(value), value);
  }

  public IPLMaterial getMaterials() {
    long cPtr = libphononJNI.IPLStaticMeshSettings_materials_get(swigCPtr, this);
    return (cPtr == 0) ? null : new IPLMaterial(cPtr, false);
  }

  public IPLStaticMeshSettings() {
    this(libphononJNI.new_IPLStaticMeshSettings(), true);
  }

}
