/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class IPLSceneType {
  public final static IPLSceneType IPL_SCENETYPE_DEFAULT = new IPLSceneType("IPL_SCENETYPE_DEFAULT");
  public final static IPLSceneType IPL_SCENETYPE_EMBREE = new IPLSceneType("IPL_SCENETYPE_EMBREE");
  public final static IPLSceneType IPL_SCENETYPE_RADEONRAYS = new IPLSceneType("IPL_SCENETYPE_RADEONRAYS");
  public final static IPLSceneType IPL_SCENETYPE_CUSTOM = new IPLSceneType("IPL_SCENETYPE_CUSTOM");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static IPLSceneType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + IPLSceneType.class + " with value " + swigValue);
  }

  private IPLSceneType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private IPLSceneType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private IPLSceneType(String swigName, IPLSceneType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static IPLSceneType[] swigValues = { IPL_SCENETYPE_DEFAULT, IPL_SCENETYPE_EMBREE, IPL_SCENETYPE_RADEONRAYS, IPL_SCENETYPE_CUSTOM };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

