/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class IPLTrueAudioNextDeviceSettings {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected IPLTrueAudioNextDeviceSettings(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IPLTrueAudioNextDeviceSettings obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(IPLTrueAudioNextDeviceSettings obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libphononJNI.delete_IPLTrueAudioNextDeviceSettings(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setFrameSize(int value) {
    libphononJNI.IPLTrueAudioNextDeviceSettings_frameSize_set(swigCPtr, this, value);
  }

  public int getFrameSize() {
    return libphononJNI.IPLTrueAudioNextDeviceSettings_frameSize_get(swigCPtr, this);
  }

  public void setIrSize(int value) {
    libphononJNI.IPLTrueAudioNextDeviceSettings_irSize_set(swigCPtr, this, value);
  }

  public int getIrSize() {
    return libphononJNI.IPLTrueAudioNextDeviceSettings_irSize_get(swigCPtr, this);
  }

  public void setOrder(int value) {
    libphononJNI.IPLTrueAudioNextDeviceSettings_order_set(swigCPtr, this, value);
  }

  public int getOrder() {
    return libphononJNI.IPLTrueAudioNextDeviceSettings_order_get(swigCPtr, this);
  }

  public void setMaxSources(int value) {
    libphononJNI.IPLTrueAudioNextDeviceSettings_maxSources_set(swigCPtr, this, value);
  }

  public int getMaxSources() {
    return libphononJNI.IPLTrueAudioNextDeviceSettings_maxSources_get(swigCPtr, this);
  }

  public IPLTrueAudioNextDeviceSettings() {
    this(libphononJNI.new_IPLTrueAudioNextDeviceSettings(), true);
  }

}
