/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class IPLTransmissionType {
  public final static IPLTransmissionType IPL_TRANSMISSIONTYPE_FREQINDEPENDENT = new IPLTransmissionType("IPL_TRANSMISSIONTYPE_FREQINDEPENDENT");
  public final static IPLTransmissionType IPL_TRANSMISSIONTYPE_FREQDEPENDENT = new IPLTransmissionType("IPL_TRANSMISSIONTYPE_FREQDEPENDENT");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static IPLTransmissionType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + IPLTransmissionType.class + " with value " + swigValue);
  }

  private IPLTransmissionType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private IPLTransmissionType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private IPLTransmissionType(String swigName, IPLTransmissionType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static IPLTransmissionType[] swigValues = { IPL_TRANSMISSIONTYPE_FREQINDEPENDENT, IPL_TRANSMISSIONTYPE_FREQDEPENDENT };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

