/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public interface libphononConstants {
  public final static int STEAMAUDIO_VERSION_MAJOR = libphononJNI.STEAMAUDIO_VERSION_MAJOR_get();
  public final static int STEAMAUDIO_VERSION_MINOR = libphononJNI.STEAMAUDIO_VERSION_MINOR_get();
  public final static int STEAMAUDIO_VERSION_PATCH = libphononJNI.STEAMAUDIO_VERSION_PATCH_get();
}
