/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class SWIGTYPE_p__IPLSerializedObject_t {
  private transient long swigCPtr;

  protected SWIGTYPE_p__IPLSerializedObject_t(long cPtr, @SuppressWarnings("unused") boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p__IPLSerializedObject_t() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p__IPLSerializedObject_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(SWIGTYPE_p__IPLSerializedObject_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

