load("//first_party/dagger:defs.bzl", "kt_jvm_library_with_dagger")

package(default_visibility = ["//visibility:private"])

kt_jvm_library_with_dagger(
    name = "dagger_library_must_build",
    srcs = ["TestComponent.java"],
)
