load("@rules_java//java:defs.bzl", "java_library")

package(
    default_visibility = ["//visibility:private"],
)

java_library(
    name = "maven_deps_must_resolve",
    srcs = ["Deps.java"],
    deps = [
        "@com_jackbradshaw_maven//:com_google_auto_auto_common",
        "@com_jackbradshaw_maven//:com_google_auto_factory_auto_factory",
        "@com_jackbradshaw_maven//:com_google_auto_value_auto_value",
        "@com_jackbradshaw_maven//:com_google_auto_value_auto_value_annotations",
        "@com_jackbradshaw_maven//:com_google_code_gson_gson",
        "@com_jackbradshaw_maven//:com_google_dagger_dagger",
        "@com_jackbradshaw_maven//:com_google_dagger_dagger_compiler",
        "@com_jackbradshaw_maven//:com_google_dagger_dagger_producers",
        "@com_jackbradshaw_maven//:com_google_guava_guava",
        "@com_jackbradshaw_maven//:com_google_protobuf_protobuf_kotlin",
        "@com_jackbradshaw_maven//:com_google_protobuf_protobuf_kotlin_lite",
        "@com_jackbradshaw_maven//:com_google_protobuf_protobuf_lite",
        "@com_jackbradshaw_maven//:com_google_truth_truth",
        "@com_jackbradshaw_maven//:io_ktor_ktor_http_jvm",
        "@com_jackbradshaw_maven//:io_ktor_ktor_server_core_jvm",
        "@com_jackbradshaw_maven//:io_ktor_ktor_server_host_common_jvm",
        "@com_jackbradshaw_maven//:io_ktor_ktor_server_netty_jvm",
        "@com_jackbradshaw_maven//:javax_inject_javax_inject",
        "@com_jackbradshaw_maven//:junit_junit",
        "@com_jackbradshaw_maven//:org_jetbrains_kotlin_kotlin_test",
        "@com_jackbradshaw_maven//:org_jetbrains_kotlinx_kotlinx_coroutines_core",
        "@com_jackbradshaw_maven//:org_jmonkeyengine_jme3_bullet",
        "@com_jackbradshaw_maven//:org_jmonkeyengine_jme3_bullet_native",
        "@com_jackbradshaw_maven//:org_jmonkeyengine_jme3_core",
        "@com_jackbradshaw_maven//:org_jmonkeyengine_jme3_desktop",
        "@com_jackbradshaw_maven//:org_jmonkeyengine_jme3_lwjgl3",
        "@com_jackbradshaw_maven//:org_jmonkeyengine_jme3_vr",
        "@com_jackbradshaw_maven//:org_lwjgl_lwjgl",
        "@com_jackbradshaw_maven//:org_skyscreamer_jsonassert",
    ],
)
