load("@rules_kotlin//kotlin:jvm.bzl", "kt_jvm_library")
load("//first_party/coroutines:publicity.bzl", "PUBLICITY")

kt_jvm_library(
    name = "idleable",
    srcs = ["Idleable.kt"],
    visibility = PUBLICITY,
)
