load("//first_party/dagger:defs.bzl", "kt_jvm_library_with_dagger")
load("//first_party/otter:publicity.bzl", "PUBLICITY")

kt_jvm_library_with_dagger(
    name = "qualifiers",
    srcs = ["Qualifiers.kt"],
    visibility = PUBLICITY,
)
