load("@rules_kotlin//kotlin:jvm.bzl", "kt_jvm_library")
load("//first_party/otter/demo:publicity.bzl", "PUBLICITY")

kt_jvm_library(
    name = "constants",
    testonly = True,
    srcs = ["Constants.kt"],
    visibility = PUBLICITY,
)
