load("@rules_kotlin//kotlin:jvm.bzl", "kt_jvm_library")

kt_jvm_library(
    name = "constants",
    testonly = True,
    srcs = ["Constants.kt"],
    visibility = ["//first_party/otter/demo:__subpackages__"],
)
