load("@rules_kotlin//kotlin:jvm.bzl", "kt_jvm_library")
load("//first_party/publicity:publicity.bzl", "PUBLICITY")

kt_jvm_library(
    name = "advancable",
    srcs = ["Advancable.kt"],
    visibility = PUBLICITY,
)
