load("@protobuf//bazel:proto_library.bzl", "proto_library")

package(default_visibility = ["//visibility:private"])

proto_library(
    name = "proto_library_must_build",
    srcs = ["message.proto"],
)
